name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  ubuntu-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Run Go Vet
        run: |
          go vet ./...

      - name: Run Go Fmt
        run: |
          files=$(go fmt ./...)
          if [ -n "$files" ]; then
            echo "Please run gofmt on these files ..."
            echo "$files"
            exit 1
          fi

      - name: Build
        run: go build -v

      - name: Run Unit Test
        run: go test -count 1 -v ./...
        
  windows-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Run Go Vet
        run: |
          go vet ./...

      - name: Build
        run: go build -v

      - name: Run Unit Test
        run: go test -count 1 -v ./...
